### ISSUE TITLE
`setup.py`: fix or kill

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#105]
Changes/improvements to `setup.py` from @juanitorduz in #79 ended up breaking the pypi build when I released version 0.0.4. I quickly fixed this with #99 by rolling back changes to `setup.py`.

At the moment, it's not clear if the error was coming from how the version is dealt with (line below works fine and is good)

https://github.com/pymc-labs/CausalPy/blob/127f384df34879dfc86c33aa9de9f49ea3b941b9/setup.py#L17

or changes to how requirements files were being read in and dealt with.

Thoughts:
- Can we actually entirely remove `setup.py` and just have `pyproject.toml`?
- If not, then:
  -  We should improve versioning, perhaps by using https://github.com/peritus/bumpversion, which will make it easier to automate the version release process.
  - See if we can revert back to @juanitorduz's improvements to how requirements were deal with, and not break the pypi build.

**Comment by juanitorduz** [comment]
I'm not very experienced in the subject but I j it about a very cool project ;) Wolt is maintaining a pretty modern python package cookie cutter from which we can get some cool tricks https://github.com/woltapp/wolt-python-package-cookiecutter It is actively maintained!

**Comment by drbenvincent** [comment]
Thanks. I don't know if this is a good idea, but the basic approach I'm trying to take is to learn by implementing everything manually, step by step. So it's slower and maybe more error prone, but hopefully I'll get a richer understanding in the end. At that point then automating with template repos or cookie cutter is probably the way forward. But yes, very wise to take inspiration from other repos!
