### ISSUE TITLE
add option to choose sampler 

### ISSUE THREAD

**Issue by matekadlicsko** [pymc-labs/CausalPy#106]
Using ```jax.sample_numpyro_nuts``` could speed sampling up by a lot. Perhaps swapping out ```sample_kwargs``` for ```sampler``` in ```ModelBuilder``` could be an easy solution?

**Comment by drbenvincent** [comment]
Hi @matekadlicsko. Yes, I think we will definitely do this. First we plan on using Bambi rather than a custom linear regression model (see #22), so we'll come and address this issue after that!

Thanks for the suggestion!

**Comment by matekadlicsko** [comment]
Hi @drbenvincent ,
Thank you! I love this project, looking forward to contribute as soon as you open it up to contributors.

**Comment by drbenvincent** [comment]
Note: since PyMC 5.1.2, you can now pass `nuts_sampler_kwargs` as a kwarg to `pm.sample` https://github.com/pymc-devs/pymc/releases/tag/v5.1.2
