### ISSUE TITLE
Timeseries experiment class reporting synthetic control label?

### ISSUE THREAD

**Issue by NathanielF** [pymc-labs/CausalPy#160]
Not entirely sure this is an issue, as the data and the plot look correct for an interrupted time-series experiment, but the label on the plot says this  posterior predictive distribution is a synthetic control which doesn't seem like the right label when there is an independent class for synthetic controls 

The original plot generated by the result.plot function
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/10588167/211768708-21c7f210-8b9a-4c69-8c11-0b961d0d7942.png">

My own plot using the result object: 

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/10588167/211769334-fe406df5-b8c1-4417-94db-366b08ee3ed2.png">

**Comment by drbenvincent** [comment]
Thanks for mentioning this - it is undesirable behaviour, if not a 'bug'. A quick fix would be totally possible, but I'm going to leave this open because there's some more thinking I'd like to do to solve a larger question first.

**Comment by drbenvincent** [comment]
This is dealt with by #200
