### ISSUE TITLE
compromised package?

### ISSUE THREAD

**Issue by thistleknot** [pymc-labs/CausalPy#172]
Everytime I run causalpy (0.10.0)
Python 3.9.9

causalpy.pymc_experiments.RegressionDiscontinuity
       
some variant of

try_march_fhia3q6t.exe 

shows up in c:\Users\User\AppData\Local\Temp

**Comment by thistleknot** [comment]
Just reinstalled and same
![image](https://user-images.githubusercontent.com/5154106/223909650-2e0349ae-0cbf-43d8-b3c5-5c67241a7ab2.png)

**Comment by twiecki** [comment]
WTH, how did you install?

**Comment by drbenvincent** [comment]
> @drbenvincent How did you upload to pypi?

I was doing this https://github.com/pymc-labs/CausalPy/blob/main/CONTRIBUTING.md#actual-release-to-pypiorg-manual, manually using my (very secure) pypi username and password.

Recently @lucianopaz made some changes. To be honest I'm not yet up to speed on how all that works. Could that have lead to a problem? https://github.com/pymc-labs/CausalPy/blob/main/CONTRIBUTING.md#actual-release-to-pypiorg-manual

https://github.com/pymc-labs/CausalPy/blob/09958f784d0c954df8f4f2512bb39471190a0f48/.github/workflows/ci.yml#L44

**Comment by drbenvincent** [comment]
There's also a PR from @lucianopaz for release automation https://github.com/pymc-labs/CausalPy/pull/163/files but that's not been merged yet.

**Comment by twiecki** [comment]
OK, I think it's very unlikely that our package is compromised then and I would expect @thistleknot's PC to be compromised. To say for sure though, we would need to know which file (.tar.gz or the wheel) was actually downloaded and just unpack that and check.

**Comment by thistleknot** [comment]
Installed via pip install causalpy

**Comment by thistleknot** [comment]
But I'll try downloading the .gz and installing that way?

**Comment by thistleknot** [comment]
Normally I wouldn't think it's a package, but I read recently that a lot of
python packages are compromised, so that's why I reached out.  I'm not sure
where it came from.  Could have hijacked my pip for all I know, but it only
happens when I load that package.

**Comment by drbenvincent** [comment]
We definitely appreciate you reaching out @thistleknot. If you install with `pip install git+https://github.com/pymc-labs/CausalPy.git` then it will download from GitHub rather than pipy. Obviously kill your previous environment and start a new one. We know the GitHub repo itself is ok, the possibility is just if the package on pipy is compromised or not.

**Comment by twiecki** [comment]
I checked both packages manually and there was no .exe file in them.

**Comment by lucianopaz** [comment]
This is actually a `theano`, `aesara`, `pytensor` issue. When `pytensor` is imported, it calls into [`try_march_flag`](https://github.com/pymc-devs/pytensor/blob/8606498fa92e86ec10f7357e4da228cfd86bced7/pytensor/link/c/cmodule.py) to set the default compilation flags. This produces an executable file that is run and removed afterwards. This might be the culprit of the avast blocker.

**Comment by twiecki** [comment]
Thanks for explaining @lucianopaz that makes sense!
