### ISSUE TITLE
Feature Request: Implementing Bayesian Networks

### ISSUE THREAD

**Issue by arainboldt** [pymc-labs/CausalPy#173]
I love PyMC and do causal analysis at work. This extension of PyMC could be really exciting. 

In response to the call to action [here](https://www.pymc-labs.io/blog-posts/causalpy-a-new-package-for-bayesian-causal-inference-for-quasi-experiments/), I'm offering a feature request to implement an API for Discrete/Continuous/Mixed Bayesian Networks with PyMC components. 

And then, perhaps, as an extension the various DAG based causal inference methods could be implemented as well ;)

Anyway, just an idea. Love your work!

**Comment by twiecki** [comment]
@arainboldt Nice idea, is that something you're interested in working on?

**Comment by drbenvincent** [comment]
Thanks for the suggestion. Just to flesh this out a bit, how would this be different from simply using PyMC itself? There's a bit of discussion about it [Bayes nets here](https://discourse.pymc.io/t/bayes-nets-belief-networks-and-pymc/5150) a while back, and about an [improved API for the do operator here](https://github.com/pymc-devs/pymc/discussions/5280)

**Comment by arainboldt** [comment]
Hey @twiecki & @drbenvincent  thanks for the quick responses. 

- how is this different:

 I don't expect it would be fundamentally different. A helpful API for defining and parameterizing models more explicitly from the Bayesnet / DAG perspective is what I'm thinking about. 

I've read through the various relevant questions and posts that I could find, including those linked. 

They're helpful, but I think there's more that can be done. 

There are a few good libraries out there that serve these needs already, but the PyMC API and environment is preferable to me and it would be nice to easily incorporate it into this part of my work.

- would I be interested in contributing

Absolutely 🤗, time permitting.

- would I be available for a call to discuss more

That'd be great! A disclaimer, I'm just getting my feet wet again in causal and bayesian modelling in a new role I started a couple months ago, after a long break. Consequently, Im still getting familiar with the problem space. Nonetheless, I'm excited to discuss and collaborate where I can. DM me to arrange whenever's convenient. Do DMs exist on GitHub? I'll create an account on the PyMC discourse

**Comment by arainboldt** [comment]
Ps. [These](https://github.com/pymc-devs/pymc/discussions/5280) are exciting ideas!

**Comment by drbenvincent** [comment]
>I'll create an account on the PyMC discourse

I'll be in touch.
