### ISSUE TITLE
Synthetic Control: allow for control of additional covariates 

### ISSUE THREAD

**Issue by SStock1** [pymc-labs/CausalPy#176]
Currently synthetic control only allows for the control of 1 covariate i.e. the outcome variable of interest. The model could be fit on all the covariates with results given for the causal impact on each covariate separately.

**Comment by drbenvincent** [comment]
Hi @SStock1. Could you elaborate a little more on what you mean here, perhaps with a link to an example. I was a bit confused by the second sentence, the wording makes it sound like you are referring to multiple outcome measures, but I'm not sure that's what you mean?

**Comment by SStock1** [comment]
Hi, @drbenvincent 

I was suggesting 

1.  Firstly allowing the inclusion of additional covariates in the design matrix.
2.  Then potentially extending this to multiple outcome variables. 

This would perhaps involve fitting the model to the entire design matrix which includes all of the covariates and then plotting and summarising the results for each outcome variable separately.

Hopefully that clears things up.

**Comment by drbenvincent** [comment]
Thanks for the clarifications. I think for (2) this would not be high on the priority list, but we're not averse to a well-done PR with an example notebook with a clear use case.

In terms of (1) I'm perhaps still a bit fuzzy, but it may be a terminology thing.

Traditional synthetic controls are built from a weighted sum of control units. All of those control units enter in to the design matrix and are used. 

Are you talking about adding other time series covariates into that weighted sum? If so, that is easy, you can just add those predictor variables into the model equation. Though I'm not sure how meaningful that would be without more info or a pointer to a paper, for example.

Or are you talking about a more elaborate model like this where you have $I$ control units like in normal synthetic control, but then also have $J$ additional linear predictor variables...

$$
\mu = \sum_i^I \beta_i \cdot control_i + \sum_j^J \gamma_j \cdot predictor_j
$$

The first term is the traditional synthetic control where the $\beta$'s sum to 1, and the second term are the extra covariates you mean with $\gamma$ being regular unconstrained regression coefficients.

**Comment by SStock1** [comment]
Thanks for the reply. I believe what I was getting at was adding other time series covariates into that weighted sum as with traditional synthetic control. I have since forked the repo and implemented this.

**Comment by drbenvincent** [comment]
Can't this be done by simply adding the term (corresponding to your desired column of data) to the model equation?

**Comment by SStock1** [comment]
I think I see what you are getting at here. 

I was talking about a model of the form:

```math
\qquad \sum_{i=1}^k \beta_i \cdot x_i
```

where in some rows of the design matrix $\mu$ and $x_i$ are the outcome variable, in this case GVA, and in some rows of the design matrix $\mu$ and $x_i$ are for another covariate to control for such as number of employees. I'm starting to question whether it makes theoretical sense to do this though from your comments.

**Comment by drbenvincent** [comment]
The goal of synthetic control is to create a synthetic version of the treated unit as a weighted sum of the untreated units.

I can't really say if putting other predictors in there makes sense or not, but it's certainly not vanilla synthetic control.

There isn't much info here about the problem being solved, so I can't say if you're on the right track or not. But I'd maybe suggest posting on the PyMC discourse about the problem to get input from people https://discourse.pymc.io/
