### ISSUE TITLE
Multiple Treatment causal impact

### ISSUE THREAD

**Issue by Starbz** [pymc-labs/CausalPy#189]
Hello,

Adding the possibility of visualizing multiple treatment would be also super helpful.

Cheers,
Arthur

**Comment by drbenvincent** [comment]
Hi @Starbz, could you flesh this out with a bit more description and perhaps linking to an example?

**Comment by Starbz** [comment]
Hi @drbenvincent , sorry for delay. Of course, the idea I had in mind was in case we were to set up a multiple treatments experiment. For instance, what if we were wanted to test 2 different increase in marketing budget over our geos. In that case we would have to select regions for synthetic control, treatment 1 and treatment 2, as well as being able to assess results post experiment.

Hope it's clear, if not feel free to reach out.

Right now, I'm using a non bayesian approach R lib from meta for this use cases, but not very effective for multiple treatments : https://facebookincubator.github.io/GeoLift/docs/intro

Thanks,
Arthur

**Comment by drbenvincent** [comment]
Thanks for expanding. Just leaving these more specific links:
* [Multi-Cell Experiments with GeoLift](https://facebookincubator.github.io/GeoLift/blog/MultiCell)
* [Multi-Cell Walkthrough](https://facebookincubator.github.io/GeoLift/docs/GettingStarted/MultiCellWalkthrough/)

**Comment by drbenvincent** [comment]
We can break down this into two separate issues:
* https://github.com/pymc-labs/CausalPy/issues/319
* https://github.com/pymc-labs/CausalPy/issues/320

I'm going to close this issue in favour of these.
