### ISSUE TITLE
`.csv` files not included in automated pypi release

### ISSUE THREAD

**Issue by Mfundo-debug** [pymc-labs/CausalPy#202]
Greetings to the pymc community, yesterday I installed causalpy to my local machine (windows 11) via anaconda prompt using the pip install github link to get the latest version, to my surprise when i try to load any of the datasets from the example I receive an error, the image will be attached below, assistance will be greatly appreciated. do let me know if I need to upload something.
![cp_load](https://github.com/pymc-labs/CausalPy/assets/71297224/923abe80-d90c-4731-9bb8-26af50034d64)

![no-dataset_cp](https://github.com/pymc-labs/CausalPy/assets/71297224/749d49aa-d71f-49c6-8901-d72f27f3e8d3)

**Comment by drbenvincent** [comment]
Hi @Mfundo-debug. I think the best way to get this working would be to use the regular pip install command `pip install CausalPy`.

Installation via `pip install git+https://github.com/pymc-labs/CausalPy.git` hasn't actually been tested at this point. I'll try to test that and see if I can reproduce the issue.

**Comment by Mfundo-debug** [comment]
I tried pip install, I encountered another issue again, now it says `
ModuleNotFoundError: No module named 'causalpy'`

**Comment by drbenvincent** [comment]
Could you try the answer here https://stackoverflow.com/a/55667399. If that doesn't work then maybe try it in a fresh environment.

**Comment by drbenvincent** [comment]
@lucianopaz Do you know if there was anything in the automated release code which somehow filters out `.csv` files? Something in this file perhaps? https://github.com/pymc-labs/CausalPy/blob/main/.github/workflows/release.yml

I think the answer [here](https://stackoverflow.com/questions/779495/access-data-in-package-subdirectory) might be insightful, but asking you at this point in case you've already dealt with an issue like this. If not, I'll give it a stab.

**Comment by Mfundo-debug** [comment]
@drbenvincent so I was right, when I said there are no csv files, please alert me asap when the bug  is sorted, I'm willing to wait for now i will use pymc 5.3 to perform some data analysis

**Comment by drbenvincent** [comment]
@Mfundo-debug This now works when installing with `pip install git+https://github.com/pymc-labs/CausalPy.git`. And it will work with `pip install causalpy` once I create a new release.

Thanks @lucianopaz for the rapid response 👍

**Comment by Mfundo-debug** [comment]
I just tested, using the following cmds
`conda create -n causal_env`
`conda activarte causal_env`
`conda install ipykernel`
`python -m install ipykernel --name=causal_env`
`pip install git+https://github.com/pymc-labs/CausalPy.git`
and it works like a charm, thanks everybody(@drbenvincent ,@lucianopaz) really appreciate it!
