### ISSUE TITLE
Add missing `scikit-learn` plots to `README.md`

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#210]
- [ ] modify `docs/source/notebooks/generate_plots.ipynb` to also generate and save the images from the `scikit-learn` version of the experiments
- [ ] add missing example for ANCOVA into `README.md`
- [ ] add missing example for Interrupted Time Series into `README.md`

**Comment by anevolbap** [comment]
In `docs/source/notebooks/` there is no `scikit-learn` version for ANCOVA or RK experiments, just ITS (SC and DiD which are already present in `README.md`).

Should those examples be created within the scope of this issue?

I started [this PR](https://github.com/pymc-labs/CausalPy/pull/307) tackling the first and third point.

**Comment by drbenvincent** [comment]
Thanks for this @anevolbap

So this issue is partly (but not fully) addressed by #307. I think we can create separate issues/PR's for new scikit-learn models (if they don't already exist).

I commented on the PR https://github.com/pymc-labs/CausalPy/pull/307 I think that PR is actually ready to merge.

**Comment by anevolbap** [comment]
@drbenvincent, I'll try to do the new scikit-learn models in a separate PR as you suggest. Afterwards, I hope to tackle more challenging issues.
