### ISSUE TITLE
Ruff linter and formater

### ISSUE THREAD

**Issue by juanitorduz** [pymc-labs/CausalPy#267]
See https://github.com/pymc-labs/pymc-marketing/issues/423 with corresponding PRs:
- https://github.com/pymc-labs/pymc-marketing/pull/424
- https://github.com/pymc-labs/pymc-marketing/pull/425
- https://github.com/pymc-labs/pymc-marketing/pull/427

Should I draft a PR?

**Comment by twiecki** [comment]
Sure! PyMC I think would also benefit.

**Comment by drbenvincent** [comment]
Sounds good. Is ruff's formatting equivalent to black but just a different implementation?

**Comment by juanitorduz** [comment]
> An extremely fast Python linter and code formatter, written in Rust.
> ...
> Drop-in parity with [Flake8](https://docs.astral.sh/ruff/faq/#how-does-ruff-compare-to-flake8), isort, and Black

Same as black but way faster!
