### ISSUE TITLE
check `Makefile` now that we use ruff

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#271]
In #268, @juanitorduz brought in use of ruff for formatting and linting. 

I'm wondering if we need to make any edits here in the listing related parts of the `Makefile`

https://github.com/pymc-labs/CausalPy/blob/2169bf0b310c29187c957bd128c8774a46ab5138/Makefile#L6-L18

**Comment by jsakv** [comment]
@drbenvincent I went through the PR steps and the makefile also need to be updated. 

I have started to have a look, I will raise a PR soon!

**Comment by drbenvincent** [comment]
Fantastic @jsakv :)

**Comment by juanitorduz** [comment]
@jsakv we have one something similar for PyMC Marketing https://github.com/pymc-labs/pymc-marketing/pull/438 :)
