### ISSUE TITLE
Inverse Propensity Score Weighting

### ISSUE THREAD

**Issue by NathanielF** [pymc-labs/CausalPy#303]
Putting an issue here to say I intend to add the functionality for inverse propensity score weighting approaches to estimating ATE. 

As discussed here: https://www.pymc.io/projects/examples/causal_inference/bayesian_nonparametric_causal.html

**Comment by drbenvincent** [comment]
Can we close this @NathanielF ?

**Comment by NathanielF** [comment]
Yes
