### ISSUE TITLE
Auto release of CausalPy 0.2.3 to PyPI failed

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#315]
See here https://github.com/pymc-labs/CausalPy/actions/runs/8569317167

Tagging @anevolbap, @juanitorduz, @jpreszler as I won't be able to get to this until next week 😭

**Comment by juanitorduz** [comment]
Not this weekend 🙈😞. I'll try early next week (never release or deploy on Fridays 😅)

**Comment by jpreszler** [comment]
Based on a quick look, I think changing the download-artifact@v3 to V4 in the release yaml may fix things. The artifact is being uploaded with V4 and based on https:// github.com/actions/download-artifact there are breaking changes and mixing the two is problematic.

**Comment by anevolbap** [comment]
> Based on a quick look, I think changing the download-artifact@v3 to V4 in the release yaml may fix things. The artifact is being uploaded with V4 and based on https:// github.com/actions/download-artifact there are breaking changes and mixing the two is problematic.

Agreed. The version mismatch arises from issue #310. It could be reverted, or we could simply update the version of download-artifact to V4. I can do either of the two.

**Comment by drbenvincent** [comment]
> Agreed. The version mismatch arises from issue #310. It could be reverted, or we could simply update the version of download-artifact to V4. I can do either of the two.

Happy for you to take this on. It's outside my area of expertise.

**Comment by anevolbap** [comment]
@drbenvincent, there is an open PR (#316) that reverts the problematic changes and hopefully fixes the auto-release issues.

**Comment by drbenvincent** [comment]
> @drbenvincent, there is an open PR (#316) that reverts the problematic changes and hopefully fixes the auto-release issues.

Great stuff. Thanks for the speedy response. In theory, if I merge this and manually trigger the release workflow, that should maybe upload 0.2.3 to pypi without having to do another version bump?

**Comment by drbenvincent** [comment]
Hmmm, re-ran the GitHub action, but that failed again

**Comment by anevolbap** [comment]
The step [Build source distribution](https://github.com/pymc-labs/CausalPy/actions/runs/8569317167/job/23497238317#logs) seems to still be using the older versions (e.g. chechout@v4 instead of v3), like it is cached. Is it possible to run it from scratch?

**Comment by drbenvincent** [comment]
I manually uploaded 0.2.3 to pypi. So the current version is now available to pip install :)
