### ISSUE TITLE
Add test for API stability for a CausalPy example in Causal Inference and Discovery in Python by Aleksander Molak

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#356]
On pages 304-307 there is an example using CausalPy in Causal Inference and Discovery in Python by @AlxndrMlk. We should create a new pytest file which tests the API to ensure that people running this code in the future are still able to replicate the results.

It should probably be done in a new test file, something like `test_api_stability.py`.

A choice will have to be about reading in the data remotely or placing it internally in this repo.

To be clear, I'm not proposing that we add that example to our docs, at least not at this point :)

**Comment by drbenvincent** [comment]
Sounds great @arthurmello! Feel free to make a start - I'll assign you to this issue now.

**Comment by arthurmello** [comment]
Thanks @drbenvincent! I just did the PR, looking forward to your review.
