### ISSUE TITLE
Direct readthedocs links to "stable" instead of "latest"?

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#362]
In #354, I believe @OriolAbril enabled both "latest" and "stable" versions of the readthedocs. At the moment, the default routes to the latest version, as in if you go to [https://causalpy.readthedocs.io/](https://causalpy.readthedocs.io/) then you actually end up at `https://causalpy.readthedocs.io/en/latest/`.

Firstly, I'm assuming that "stable" corresponds to the latest GitHub release, not what is on `main`, and that "latest" corresponds to what is on `main`? Is that right?

I'm wondering if it makes sense to automatically route through to "stable" docs. That way, if we merge a PR that provides new documentation about a feature which is not fully available in the latest release, then people won't get confused.

Thoughts welcome. Would this just be a matter of changing a setting in readthedocs web ui?

**Comment by OriolAbril** [comment]
> Firstly, I'm assuming that "stable" corresponds to the latest GitHub release, not what is on main, and that "latest" corresponds to what is on main? Is that right?

That is right yes. They are both active by default in readthedocs (I am actually not sure if it is possible to turn either off) but as not all repos have releases the default is `latest`. Once a release is done (aka tags are present) then `stable` is also generated as the alias to the latest **release** and can be manually set as default.

> Would this just be a matter of changing a setting in readthedocs web ui?

Yes, go to the admin page and there is a dropdown where you can choose the default version.
