### ISSUE TITLE
Add causal videos from PyMC / PyMC Labs community

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#374]
Add a new page under the Knowledge Base which contains causal inference videos put out by the broad PyMC community. Existing videos would be:
* https://www.youtube.com/watch?v=0PQ8BQaDP04
* https://www.youtube.com/watch?v=b47wmTdcICE
* https://www.youtube.com/watch?v=QAzAFess1AA

**Comment by ParthJohri** [comment]
Greetings @drbenvincent, I would like to work on this issue, can you please assign it to me?

I would like to confirm my understanding for this issue:-

![Screenshot 2024-06-26 at 23 09 24](https://github.com/pymc-labs/CausalPy/assets/76129377/e7df81cd-cf47-43ae-9606-848c1e8e8f21)

1. Create a page like this as shown in the above screenshot.
2. Add the existing 3 videos links into that page.

**Some queries:-**
Q1. What should be the title of the page.
Q2. Apart from adding YouTube videos, do we need to add any other documentation.

Please correct me, if I misunderstood anything?
Thank you!

**Comment by drbenvincent** [comment]
Thanks @ParthJohri :)

Just to note that we've just changed the theme of the docs, so if you update from `main` and build the docs locally then it will look more like this
<img width="1189" alt="Screenshot 2024-06-26 at 18 46 23" src="https://github.com/pymc-labs/CausalPy/assets/6765047/8e53ec77-ab17-45ee-b30b-627c2e3f6b90">

You may also need to rebuild your environment as we've updated the dependencies for building the docs.

But yes, a doc in the knowledge base section as you have is great. Maybe we can call it "Causal video resources".

Check the example of the embedded video on the home page if you need to.

I think for _this issue_ we could just have the embedded videos. But there are new quite a few docs related issues which you are welcome to work on next if you like :)

Just let me know if you run into any issues.

**Comment by ParthJohri** [comment]
Thanks @drbenvincent , sure will reach out to you, if I encounter any issues.

**Comment by ParthJohri** [comment]
Hi @drbenvincent, 
Please review the [PR](https://github.com/pymc-labs/CausalPy/pull/379) and let me know if any other changes need to be made.
Thank you!

**Comment by drbenvincent** [comment]
Thanks! I'll be able to review in the next 12-24 hours
