### ISSUE TITLE
Improve visual appearance of tables in docs

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#375]
Under the new theme tables look like this
![Screenshot 2024-06-26 at 13 20 12](https://github.com/pymc-labs/CausalPy/assets/6765047/c71434e9-16db-43b1-98df-067373de1773)

and when the mouse hovers over a row, we get a highlight like this
![Screenshot 2024-06-26 at 13 19 50](https://github.com/pymc-labs/CausalPy/assets/6765047/e547952c-1315-4793-95f4-7f561749c77d)

I think this is far from optimal. It would be good see what someone is capable of doing with custom css.

**Comment by HarisMughal** [comment]
@drbenvincent  can I work on this? How about making it match the CausalPy theme (blue and green) or just gray?

**Comment by drbenvincent** [comment]
Hi @HarisMughal. Feel free to give it a go! I think a coloured highlight makes sense. If the current one is a theme option, maybe it makes sense to change that colour site wide?

**Comment by Mark0047** [comment]
**For Dark Mode**
![image](https://github.com/pymc-labs/CausalPy/assets/26966070/70a811c0-83b6-40ef-be70-c15a63dc1dbd)
**For Light Mode with new cell spaces**
![image](https://github.com/pymc-labs/CausalPy/assets/26966070/6ce9777e-bb76-4917-a1a0-277dc73b3eaf)

Code 
`
html[data-theme="light"]{
  --pst-color-table-row-hover-bg: #83db66;
  --pst-color-secondary:#83db66;
}


html[data-theme="dark"] {
  --pst-color-table-row-hover-bg: #093e60;
  --pst-color-secondary:#093e60;
}

.table td ~ td, .table td ~ th, .table th ~ td, .table th ~ th{
  border-left-width: 1.5px;
}`

Furthermore, I believe we need to revamp the whole theme as other items (buttons, search, hover) are still following default theme I tried to change color and looks really and makes more sense!  Have a look

![image](https://github.com/pymc-labs/CausalPy/assets/26966070/8482b134-733b-4d58-bc3c-5ba28ecbc78a)
![image](https://github.com/pymc-labs/CausalPy/assets/26966070/cef0953c-b0f0-404b-be97-8f984f185833)
Shall I report a new issue for this ? @drbenvincent

**Comment by Mark0047** [comment]
Any update? @drbenvincent

**Comment by drbenvincent** [comment]
Sorry for the slow reply @Mark0047. I just want to get @OriolAbril 's opinion on editing the theme. We have a number of sites all using this theme so I want to check if specialising this one is going to cause headaches in the future?

**Comment by Mark0047** [comment]
Yes please would love to hear senior's analysis.

And shall I push the code for table?

**Comment by OriolAbril** [comment]
To keep the theme consistent across libraries we have decided to abstract the theme configuration and then use that "custom theme", see https://github.com/pymc-labs/CausalPy/pull/385.

**Comment by drbenvincent** [comment]
So now the theme is here https://github.com/pymc-labs/labs-sphinx-theme and outside of my direct control. I think it makes most sense to either leave this, or propose a change on the new `labs-sphinx-theme` repo.
