### ISSUE TITLE
Plots don't appear when running from ipython session

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#86]
So far I've exclusively been working in notebooks, and the plotting is fine. But when running the Quickstart in an ipython session then the plots do not appear.

**Comment by drbenvincent** [comment]
Yep - I think this is actually expected behaviour. I believe when I created the issue it was just an observation that running the quick start code didn't result in a plot. But I think most people should be aware that they have to add `plt.show()`. So we can probably close this issue.

**Comment by OriolAbril** [comment]
Another option could be to import matplotlib and add `plt.show()` explicitly. It won't do anything but won't bread the code either if running on a notebook but might help avoid expectations missmatch. We do have comments from this from time to time as ArviZ issues, it is a very common pain point for people who already know programming in other languages or even python but don't know how matplotlib works. If we expect this library to be an entry point into python/matplotlib world it is probably a good idea to ensure copy pasting the quickstart into ipython does generate a plot as is.

**Comment by drbenvincent** [comment]
I think that's a good idea. Do you want to have a go or shall I?

**Comment by OriolAbril** [comment]
I'll add it to the PR
